"use strict";
// UNION TYPES.
// let a: string | number | boolean | undefined;
// a = "Abdul";
// // a = 19;
// // a = true;
// console.log(a);
// // METHODS:
// let name1: string = "ABDUL";
// console.log(name1.charAt);
// console.log(name1.charCodeAt);
// console.log(name1.codePointAt);
// console.log(name1.concat);
// console.log(name1.endsWith);
// console.log(name1.includes);
// console.log(name1.indexOf);
// console.log(name1.lastIndexOf);
// console.log(name1.length);
// console.log(name1.localeCompare);
// console.log(name1.match);
// console.log(name1.normalize);
// console.log(name1.repeat);
// console.log(name1.search);
// console.log(name1.replace);
// console.log(name1.search);
// console.log(name1.slice);
// console.log(name1.split);
// console.log(name1.startsWith);
// console.log(name1.substring);
// console.log(name1.toLocaleLowerCase);
// console.log(name1.toLocaleUpperCase);
// console.log(name1.toLowerCase);
// console.log(name1.toString);
// console.log(name1.toUpperCase);
// console.log(name1.trim);
// console.log(name1.valueOf);
// console.log(name1.anchor);
// console.log(name1.big);
// console.log(name1.blink);
// console.log(name1.bold);
// console.log(name1.fixed);
// console.log(name1.fontcolor);
// console.log(name1.italics);
// console.log(name1.link);
// console.log(name1.small);
// console.log(name1.strike);
// console.log(name1.sub);
// console.log(name1.substr);
// console.log(name1.sup);
// let age: number = 18;
// console.log(age.toExponential());
// console.log(age.toFixed(2));
// console.log(age.toLocaleString());
// console.log(age.toPrecision(2));
// console.log(age.toString(2));
// console.log(age.valueOf());
// let id1: string | number ;
// id1.toLocaleString
// id1.toString
// id1.valueOf
